### ISSUE TITLE
Module with Docs instead of Control Repo

### ISSUE THREAD

**Issue by RARYates** [puppetlabs/puppet-vro-starter_content#35]
Our plugin referencing a control-repo full of forked modules is an anti-pattern to what we teach puppet users. Users could potentially adopt this control repo or parts of it, and end up paying across the rest of their infrastructure in technical debt.

Can we work on transitioning this into a module that sets our master to be compatible with the Plugin (manages sudoers, autosign, etc), and documentation on linking a vRO implementation with a master that has the module included?

**Comment by jpadams** [comment]
Thanks, @RARYates, we should be transitioned more to the model you want now with

https://github.com/puppetlabs/puppet-vro-starter_content/blob/production/Puppetfile#L35-L44

You can use the plugin prep module on its own. This repo is an example using it.

**Comment by RARYates** [comment]
Awesome! Will it be ported into this repo, or delivered via new one?

**Comment by jpadams** [comment]
@RARYates it has its own repo here: 

https://github.com/puppetlabs/puppet-vra_puppet_plugin_prep

I'll close this for now. Let me know if that doesn't work. Thanks, again!

**Comment by RARYates** [comment]
This is great, thank you very much! Next time I run into a big VMWare
client, I'll make some PRs against the repo for modularity so they can
manage sshd_config or other weird things externally if they have competing
profiles.
