### ISSUE TITLE
Ubuntu 18.04 and Puppet Enterprise 2019.1.1 Issues

### ISSUE THREAD

**Issue by tomburge** [puppetlabs/puppet-vro-starter_content#41]
## Describe the Bug
Error:

Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for puppet.home.lab
Info: Applying configuration version '1565636919'
Error: Could not prefetch rbac_role provider 'ruby': SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure
Error: Failed to apply catalog: SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure

## Expected Behavior
Notice: Applied catalog in 25.74 seconds

## Steps to Reproduce

wget -O - https://downloads.puppetlabs.com/puppet-gpg-signing-key.pub | gpg --import
curl -JLO https://pm.puppet.com/cgi-bin/download.cgi?dist=ubuntu&rel=18.04&arch=amd64&ver=latest
tar -xzvf puppet-enterprise-2019.1.1-ubuntu-18.04-amd64.tar.gz
cd puppet-enterprise-2019.1.1-ubuntu-18.04-amd64/
sudo ./puppet-enterprise-installer

Option 1

Follow the link to set the password

sudo puppet agent -t
sudo puppet agent -t
sudo apt-get install python
git clone https://github.com/puppetlabs/puppet-vro-starter_content.git
cd puppet-vro-starter_content
sudo bash scripts/vra_nc_setup.sh
sudo puppet agent -t

## Environment
 - Version Puppet 6.4.3 or Puppet Enterprise 2019.1.1
 - Platform Ubuntu 18.04

## Additional Context
This is a fresh install

**Comment by bmjen** [comment]
Hi @tomburge , I think this may be an SSL issue. I believe PE 2019.1.1 defaults to TLS 1.2. Are you running an updated version of openssl on the Ubuntu node? What is the output of running the following command on the agent node.

`openssl s_client -connect <PE master>:443 -tls1_2`

**Comment by bmjen** [comment]
@tomburge #40 should fix this issue. Please pull the update from `production` and run puppet agent to deploy the fix.

**Comment by tomburge** [comment]
How would I pull a specific update from production? Never done that.

**Comment by tomburge** [comment]
Nevermind. I got it. No more error. Thanks!
